#!/bin/bash

[[ $ZTF_TEST_00_COMPILE -ne 0 ]] && { echo "no succesful compile"; exit 1; }

# this should work otherwise
cd $RDUP_SOURCE

mkdir aaa
touch aaa/A
touch aaa/b
touch aaa/c
touch aaa/d
touch aaa/e
touch aaa/f
touch aaa/r
cd aaa
ln -sf b def
cd ..
./rdup /dev/null aaa | grep -- '+l'
RET=$?
rm -rf aaa
exit $RET
