#!/bin/bash

[[ $ZTF_TEST_00_COMPILE -ne 0 ]] && { echo "no succesful compile"; exit 1; }

# this should work otherwise
cd $RDUP_SOURCE

rm -rf t tmp

mkdir t tmp
touch t/foo
(cd t; ln -s foo bar)

# still uses stuff from $PATH
./sh/rdup-simple.sh t tmp
DAY_BEFORE=$(( $(date +%d) - 1 )) # may be 0
DATE=$(date +%Y%m)
NOW=$(date +%d)
mv tmp/$DATE/$NOW tmp/$DATE/$DAY_BEFORE

rm t/bar
./sh/rdup-simple.sh t tmp
EXIT=$?

rm -rf t tmp
exit $EXIT
