#!/bin/bash

TL=/var/svn/rdup
PATH=$PATH:/usr/local/bin:/usr/local/sbin:.
TPKG=/home/miekg/svn/tpkg/trunk/tpkg

SVN_BAR="------------------------------------------------------------------------"

REPOS="$1"
REV="$2"

START=`date +%s`
export BUILD_DIR=`mktemp -d /tmp/XXXXXX`
export MAIL_FILE=`mktemp /tmp/XXXXXXX`
# if svnlook does not return a full path with a file
# this will fail
LOOK=`/usr/bin/svnlook changed -r$REV $TL | /usr/bin/awk '{ print $2 }' | head -1`
if [[ $LOOK =~ '^trunk' ]]; then
        BRANCH="trunk"
fi
if [[ $LOOK =~ '^branches' ]]; then
        BRANCH=`echo $LOOK | cut -f1,2 -d /`
fi
if [[ $LOOK =~ '^tags' ]]; then
        BRANCH=`echo $LOOK | cut -f1,2 -d /`
fi

(
# checkout to $BUILD_DIR
/usr/bin/svn co -r$REV file://$REPOS/$BRANCH $BUILD_DIR
( cd $BUILD_DIR ; svn log -r$REV > $MAIL_FILE )
svnlook changed -r$REV $TL >> $MAIL_FILE
echo $SVN_BAR >> $MAIL_FILE

echo "PATH=$PATH" > $BUILD_DIR/test/.tpkg.var.master
echo "TPKG_BUILD=$BUILD_DIR" >> $BUILD_DIR/test/.tpkg.var.master

# RUN THE TESTS
for tests in $BUILD_DIR/test/*.tpkg
do
        /usr/bin/nice /bin/bash \
       $TPKG -b $BUILD_DIR/test -a $BUILD_DIR exe `basename $tests`
done

END=`date +%s`
echo ELAPSED: $((END - START)) s >> $MAIL_FILE
echo $SVN_BAR >> $MAIL_FILE

/bin/bash $TPKG -b $BUILD_DIR/test report >> $MAIL_FILE
/bin/bash $TPKG -b $BUILD_DIR/test clean
# END

# SVN STUFF
( cd $BUILD_DIR ; svn diff -rPREV:$REV >> $MAIL_FILE )

rm -rf $BUILD_DIR

cat $MAIL_FILE | \
mail -s "[svn: rdup|$BRANCH] r$REV status" miek@atoom.net
rm -f $MAIL_FILE
) &
