#!/bin/bash

mkdir -p A/a A/b A/d
touch A/a/1 A/a/2 A/a/3
touch A/b/1 A/b/2 A/b/3
touch A/d/1 A/d/2 A/d/3
for i in e f g h i k l m n; do touch A/$i ; done

# full dump
./rdup -N $$.timestamp $$.lijst A > /dev/null

# this is why new_dir has been removed from crawler.c
( cd A
mkdir j )

# we no files expect to be included in the backup
./rdup -N $$.timestamp $$.lijst A> $$.diff

echo "+d 0755 0 0 5 0 /home
+d 0755 1000 1000 11 0 /home/miekg
+d 0775 1000 1000 15 0 /home/miekg/svn
+d 0775 1000 1000 20 0 /home/miekg/svn/rdup
+d 0775 1000 1000 22 0 /home/miekg/svn/rdup/A
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/a
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/b
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/d
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/j" \
 | diff - $$.diff

if [[ $? -ne 0 ]]; then
    ERROR=1
fi

rm $$.timestamp
rm $$.lijst
rm $$.diff
rm -rf A

case $ERROR in
    0)
    exit 0
    ;;
    1)
    echo "dir move failure"
    exit 1
    ;;
esac
