#!/bin/bash

mkdir -p A/a A/b
touch A/a/1 A/a/2 A/a/3
touch A/b/1 A/b/2 A/b/3

# full dump
./rdup -N $$.timestamp $$.lijst A > /dev/null

( cd A
mv a c	# swap
mv b a
mv c b )

# we expect a b to be included in the backup
./rdup -N $$.timestamp $$.lijst A >> $$.diff

echo "-d 0775 0 0 24 0 /home/miekg/svn/rdup/A/a
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/a/1
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/a/2
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/a/3
-d 0775 0 0 24 0 /home/miekg/svn/rdup/A/b
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/b/1
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/b/2
-- 0664 0 0 26 0 /home/miekg/svn/rdup/A/b/3
+d 0755 0 0 5 0 /home
+d 0755 1000 1000 11 0 /home/miekg
+d 0775 1000 1000 15 0 /home/miekg/svn
+d 0775 1000 1000 20 0 /home/miekg/svn/rdup
+d 0775 1000 1000 22 0 /home/miekg/svn/rdup/A
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/a
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/a/1
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/a/2
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/a/3
+d 0775 1000 1000 24 0 /home/miekg/svn/rdup/A/b
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/b/1
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/b/2
+- 0664 1000 1000 26 0 /home/miekg/svn/rdup/A/b/3" \
 | diff - $$.diff

if [[ $? -ne 0 ]]; then
    ERROR=1
fi

rm $$.timestamp
rm $$.lijst
rm $$.diff
rm -rf A

case $ERROR in
    0)
    exit 0
    ;;
    1)
    echo "dir move failure"
    exit 1
    ;;
esac
