#!/bin/bash
S_ISDIR=16384   # octal: 040000
S_MMASK=4095    # octal: 00007777, mask to get permissions
backupdir=$1
suffix=`date +%Y%m%d.%H:%M`  # YYYYMMDD.HH:MM
if [ -z $backupdir ]; then 
        backupdir="/tmp/storage"
fi
mkdir -p $backupdir

# process the output from rdump
while read mode uid gid path
do
        dump=${mode:0:1}        # to add or remove
        mode=${mode:1}          # st_mode bits

        # Get the permission bits
        bits=$(($mode & $S_MMASK))
        bits=`printf "%o" $bits` # and back to octal again

        # Find out of its a dir or file
        if [[ $(($mode & $S_ISDIR)) == $S_ISDIR ]]; then
                dir=1;
        else 
                dir=0;
        fi
        
        if [[ $dump == "+" ]]; then
                # add
                if [[ $dir == 1 ]]; then
                        echo "mkdir -p $backupdir/$path"
                else
                        echo "cat $path | gzip -c > $backupdir/$path"
                fi
                echo "chown $uid:$gid $backupdir/$path"
                echo "chmod $bits $backupdir/$path"
        else
                # remove
                if [[ $dir == 1 ]]; then
                        echo "mv $backupdir/$path $backupdir/$path.$suffix"
                else
                        echo "mv $backupdir/$path $backupdir/$path.$suffix"
                fi
        fi
done 
