#!/bin/bash
S_ISDIR=16384   # octal: 040000
S_MMASK=4095    # octal: 00007777, mask to get permissions
backupdir=$1
suffix=`date +%Y%m%d.%H:%M`  # YYYYMMDD.HH:MM
if [ -z $backupdir ]; then 
        backupdir="/tmp/storage"
fi
mkdir -p $backupdir

while read mode uid gid path
do
        dump=${mode:0:1}        # to add or remove
        mode=${mode:1}          # st_mode bits

        bits=$(($mode & $S_MMASK)) # permission bits
        bits=`printf "%o" $bits` # and back to octal again

        dir=0
        if [[ $(($mode & $S_ISDIR)) == $S_ISDIR ]]; then
                dir=1;
        fi
        
        if [[ $dump == "+" ]]; then
                # add
                if [[ $dir == 1 ]]; then
                        [ ! -d $backupdir/$path ] && mkdir -p $backupdir/$path
                else
                        cat $path > $backupdir/$path
                fi
                chown $uid:$gid $backupdir/$path
                chmod $bits $backupdir/$path
        else
                # remove
                mv $backupdir/$path $backupdir/$path.$suffix
        fi
done 
