#!/bin/bash

# somewhere, someone has given us a env vars which
# states WHERE the source of rdup lives

[[ -z $RDUP_SOURCE ]] && { echo "No source found"; exit 1; }

cd $RDUP_SOURCE

case $OSTYPE in
    linux*)
	autoreconf && ./configure && make
    ;;
    freebsd*)
	autoconf && ./configure && gmake
   ;;
esac
