#!/bin/bash

[[ $ZTF_TEST_00_COMPILE -ne 0 ]] && { echo "no succesful compile"; exit 1; }

# this should work otherwise
cd $RDUP_SOURCE
./rdup /dev/null test | ./rdup-tr -Pcat -Pgzip,-c,-f -Pcat -Otar | tar tvf -
