#!/bin/bash

[[ $ZTF_TEST_00_COMPILE -ne 0 ]] && { echo "no succesful compile"; exit 1; }
# this should work otherwise
cd $RDUP_SOURCE

rm -rf A

mkdir -p A/a A/b A/d
touch A/a/1 A/a/2 A/a/3
touch A/b/1 A/b/2 A/b/3
touch A/d/1 A/d/2 A/d/3
for i in e f g h i k l m n; do touch A/$i ; done

# full dump
./rdup -N $$.timestamp $$.lijst A > /dev/null

# this is why new_dir has been removed from crawler.c
( cd A
mkdir j )

# files to expect to be included in the backup
./rdup -N $$.timestamp $$.lijst A | \
 awk 'FS="/" { print substr($0,length($1 $2 $3 $4) + 4) } ' | \
 tail -n +4  > $$.diff

echo "/a
/b
/d
/j" | diff - $$.diff

if [[ $? -ne 0 ]]; then
    ERROR=1
fi

rm $$.timestamp
rm $$.lijst
rm $$.diff
rm -rf A

case $ERROR in
    0)
    exit 0
    ;;
    1)
    echo "dir move failure"
    exit 1
    ;;
esac
