#!/bin/sh

# get the path were we live
if [[ $0 =~ ^/ ]]; then
        p=$0
 else
        p=`pwd`/$0
fi

d=`date +%Y%m`
mountpath=`dirname $p`
echo $mountpath
echo $d
# $mountpath/$HOSTNAME/etc - etc/adm dir
# $mountpath/$HOSTNAME/$date - backup dir

# only to get root 
echo gksudo -m "Perform backup of $HOSTNAME to $mountpath as root?" -t "rdup @ $HOSTNAME" "cat /dev/null"
if [[ $? -ne 0 ]]; then
        exit
fi

## Set the directories ##
STAMP="$mountpath/$HOSTNAME/$HOSTNAME.timestamp"
LIST="$mountpath/$HOSTNAME/$HOSTNAME.list"
BACKUPDIR="$mountpath/$HOSTNAME/$d"

# createte top-level backup dir
echo sudo mkdir -p "$mountpath/$HOSTNAME"

if [[ ! -d "$BACKUPDIR" ]]; then
        # kill the timestamp and inc list
        echo      mkdir -p "$BACKUPDIR"
        echo      rm -f "$LIST"
        echo      rm -f "$STAMP"
fi


case $HOSTNAME in
        elektron*)
        DIRS="   "
echo    /usr/sbin/rdup -N "$STAMP" "$LIST" $DIRS \
        /usr/sbin/mirror.sh -b "$BACKUPDIR"

        ;;

        floep*)
        DIRS="   "
echo    /usr/sbin/rdup -N "$STAMP" "$LIST" $DIRS \
        /usr/sbin/mirror.sh -b "$BACKUPDIR"
        ;;
esac
