#!/bin/bash

[[ -z $ZTF_TEST_00_COMPILE ]] && { echo "no succesful compile"; exit 1; }
# this should work otherwise
cd $RDUP_SOURCE

NUM=$(./rdup -r /dev/null . | wc -l)
echo "FILES FOUND $NUM"
[[ $NUM -eq 0 ]] && exit 0
exit 1
