#!/bin/bash

[[ $ZTF_TEST_00_COMPILE -ne 0 ]] && { echo "no succesful compile"; exit 1; }
# this should work otherwise
cd $RDUP_SOURCE
# needs to be redone
exit 1

# cleanup
rm -rf A

mkdir -p A/a A/b
touch A/a/1 A/a/2 A/a/3
touch A/b/1 A/b/2 A/b/3

# only interested in the names
# awk foo!
./rdup -N $$.timestamp $$.lijst A | \
 awk 'FS="/" { print substr($0,length($1 $2 $3 $4 $5 $6) ) } ' | \
 tail -n +4  > $$.diff

# this should be the diff
echo "/a
/a/1
/a/2
/a/3
/b
/b/1
/b/2
/b/3" | diff - $$.diff

if [[ $? -ne 0 ]]; then
    ERROR=1
fi

./rdup -N $$.timestamp $$.lijst A | \
 awk 'FS="/" { print substr($0,length($1 $2 $3 $4) + 4) } ' | \
 tail -n +4 > $$.diff

echo "/a
/b" | diff - $$.diff

if [[ $? -ne 0 ]]; then
    ERROR=2
fi

rm $$.timestamp
rm $$.lijst
rm $$.diff
rm -rf A

case $ERROR in
    0)
    exit 0
    ;;
    1)
    echo "full dump error"
    exit 1
    ;;
    2)
    echo "inc dump error"
    exit 1
    ;;
esac
